const LoginAction = {
    SET_ERROR_TEXT: 'SET_ERROR_TEXT',
    RECEIVE_COMPANIES: 'RECEIVE_COMPANIES',
    SET_SELECTED_COMPANY: 'SET_SELECTED_COMPANY',
    SET_USER_ID: 'SET_USER_ID',
    SET_PASSWORD: 'SET_PASSWORD',
    SET_CHECKING_LOGIN: 'SET_CHECKING_LOGIN',
    SET_LOGIN_LOADING: 'SET_LOGIN_LOADING',
    SET_NEEDS_REDIRECT: 'SET_NEEDS_REDIRECT',
    RESET_LOGIN_STATE: 'RESET_LOGIN_STATE'
};

export default LoginAction;