export const LoginAction = {
    RECEIVE_EMPLOYEES: 'RECEIVE_EMPLOYEES',
    SET_USER_ID: 'SET_USER_ID',
    SET_COMPANY: 'SET_COMPANY',
    SET_PASSWORD: 'SET_PASSWORD',
    SET_LOADING: 'SET_LOADING',
    FETCH_COMPANIES: 'FETCH_COMPANIES',
    RECEIVE_COMPANIES: 'RECEIVE_COMPANIES',
    SET_SELECTED_COMPANY: 'SET_SELECTED_COMPANY',
    SET_NEEDS_REDIRECT: 'SET_NEEDS_REDIRECT',
};