export const FilterAction = {
    SET_FILTER: 'SET_REQUEST_FILTER',
    CLEAR_FILTER: 'CLEAR_REQUEST_FILTER'
};

export const RequestAction = {
    SET_REQUESTS_LOADING: 'SET_REQUESTS_LOADING',
    SET_EMPLOYEES: 'SET_EMPLOYEES',
    SET_SELECTED_EMPLOYEES: 'SET_SELECTED_EMPLOYEES',
    SET_FILTERED_EMPLOYEES: 'SET_FILTERED_EMPLOYEES',
};